.github/workflows/main.yml
.gitignore
README.md
server/konnection/settings.py
server/requirements.txt

* Added documentation for connecting postgres to django
* Successfully connected postgres to django
* Get the .env file from me :)

Connect postgresql to django

---

server/author/serializers.py
server/author/tests/test_create_author_endpoint.py
server/author/views.py

This is a quick fix pr to return id on login and return 401 if user is not admin approved.

[n/a] fix: login 

---

server/author/tests/test_create_author_endpoint.py
server/author/urls.py
server/author/views.py

This pr is to enhance retrieving user profile workflow but providing another endpoint `/server/author/me` to allow authenticated user to get their user profile. 
Resolve n/a

[n/a] feat: me endpoint

---

client/src/components/Feeds/MyFeedPage.js

* Populated my feed with all my public posts
* populating my feed with inbox will be done on another PR

feat: post posts to my stream

---

server/followers/tests/tests_follower_list_endpoint.py
server/followers/views.py
server/main/models.py

This pr is to fix the current issue of duplicated followers on user sign up and superuser creation. 
**Note**: Test will be included in the up coming pr.

[n/a] fix: fix follower duplication 

---

server/inbox/models.py
server/inbox/tests/test_inbox_endpoint.py
server/inbox/views.py

Added check for existing Inbox when Author is created, fixed duplicate Inbox.

fix: duplicate inbox

---

server/author/apps.py
server/followers/serializers.py
server/followers/tests/tests_follower_list_endpoint.py
server/followers/views.py

This pr is to add test to previously incomplete testing for follower API.

[n/a] test: Add test to followers API

---

server/inbox/tests/test_inbox_endpoint.py
server/inbox/views.py
server/posts/tests/test_create_post_endpoint.py
server/posts/views.py

When a Post is created, send it to followers'/friends' Inbox depending on Post visibility

feat: send Post to Inbox when Post is created

---

.github/workflows/deployment.yml
client/server.js

This pr is fix production bug.

[n/a] fix: FE prod shut down

---

server/inbox/models.py
server/inbox/views.py
server/posts/tests/test_create_post_endpoint.py
server/posts/urls.py
server/posts/views.py

Reverts C404TEAMW21/CMPUT404_PROJECT#98

Revert "feat: share post to an Author"

---

client/package-lock.json
client/src/components/Feeds/MyFeedPage.js
client/src/components/Post/CreatePostPage.js
client/src/components/Post/PostComponent.js

* Tested `As an author, other authors cannot modify my shared to friends post.`
* Tested `As an author, I can delete my public posts`
* Tested `As an author, I want to feel safe about sharing images and posts with my friends – images shared to friends should only be visible to friends. [public images are public]`
* Tested `As an author, posts I create can be private to my friends [Backend, Frontend]`

fix: delete and edit button visibility for non-public posts

---

server/inbox/models.py
server/inbox/tests/test_inbox_endpoint.py
server/inbox/views.py
server/posts/tests/test_create_post_endpoint.py
server/posts/urls.py
server/posts/views.py

factorize code to use Friends functionaility

feat: use Friends in share Post

---

README.md

[n/a] update: readme

---

server/inbox/tests/test_inbox_endpoint.py
server/inbox/views.py
server/posts/views.py

Fixed
- Inbox DELETE returning 204, changing it to 200 OK
- Share Post: check empty body

fix: Inbox fix

---

server/konnection/settings/base.py

This pr is to add basic auth support into our application.

[n/a] feat: add basic auth support

---

requirements.txt

This pr is to update current requirement file for deployment.

[n/a] fix: update requirement file 

---

server/nodes/models.py

Node password wasn't saved correctly after re-saving. Now fixed.

set node password after changes

---

server/comments/models.py
server/inbox/serializers.py
server/inbox/tests/test_inbox_endpoint.py
server/main/models.py
server/main/tests/test_models.py
server/main/utils.py
server/posts/models.py

- all URLs now point to https://konnection-client.herokuapp.com
- fix double slash '//' in url
- fix tests

Change all URLs

---

.github/workflows/deployment.yml
client/src/ApiUtils.js
client/src/Constants.js
client/src/components/Profile/ProfilePage.js
client/src/components/Profile/ProfilePage.scss
client/src/components/Profile/ProfileSearchBar.js
client/src/components/SignupLogin/LoginPage.js
client/src/components/SignupLogin/SignupLoginPage.scss
client/src/components/SignupLogin/SignupPage.js

Summary:
- created component for search profile
- call partner servers to get all authors
.env file will be sent via email

Profile Search Bar

---

client/src/ApiUtils.js
client/src/components/Feeds/MyFeedPage.js
client/src/components/Feeds/PublicFeedPage.js
client/src/components/Post/CreatePostPage.js
client/src/components/Post/PostComponent.js
client/src/components/Profile/EditProfileModal.js
client/src/components/SignupLogin/LoginPage.js
client/src/components/SignupLogin/SignupPage.js
server/author/tests/test_create_author_endpoint.py
server/comments/tests/test_comments_endpoint.py
server/followers/tests/tests_follower_list_endpoint.py
server/inbox/tests/test_inbox_endpoint.py
server/inbox/views.py
server/konnection/urls.py
server/likes/tests/test_likes_endpoints.py
server/likes/tests/test_models.py
server/likes/views.py
server/posts/tests/test_create_post_endpoint.py
server/posts/views.py

- Updated backend endpoint from /service/ to /api/
- Updated frontend to use /api/
- Backend test cases passed

Change endpoint from service to api

---

server/followers/views.py

Quick fix to the not follower endpoint

[n/a] fix: quick fix for logic

---

server/inbox/views.py
server/posts/views.py

- share Post to remote friends
- share Post to "all" including remote friends

Remote inbox functionality

---

server/followers/tests/tests_follower_list_endpoint.py
server/followers/views.py
server/posts/tests/test_create_post_endpoint.py

This pr introduced the functionality to follow and unfollow remote friends. 
Testing will be covered in the coming pr.

[n/a] feat: remote friend request and unfollow 

---

server/posts/tests/test_create_post_endpoint.py
server/posts/views.py

- Share to local followers on public Post creation
- Share to remote followers on public Post creation
- Share to local friends on friends Post creation
- Share to remote friends on friends Post creation

Share on Post creation

---

server/posts/views.py

fix: share to friend on Post creation.

fix: share to friend on Post creation.

---

server/posts/views.py

pls approve 
add check for team 6

check for team 6.

---

requirements.txt
server/followers/tests/test_follwers_server.py
server/requirements.txt

This pr is to add testing to remote server we mocks.

[n/a] test: Remote server

---

README.md
server/followers/views.py

Clean up some of the code and update readme references

[n/a] fix: magic string and update readme

---

server/main/models.py

displayname added automatically if not provided

---

client/README.md
client/src/components/Comments/CommentComponent.js
client/src/components/Comments/CommentList.js
client/src/components/Comments/Comments.scss
client/src/components/Comments/PostComments.js
client/src/components/Post/PostComponent.js
client/src/components/Post/PostList.js
client/src/components/SpecificPost/SpecificPostPage.js

**Summary:**
Set up the ui components for comments.

feat: comments UI

---

server/comments/models.py
server/comments/urls.py
server/comments/views.py
server/posts/models.py

* For creating a Remote Post:
* POST /api/author/<post_owner_id>/posts/<post_id>/create_remote_comments
* Example payload (note the `comment_url` field):
```
{
"type": "comment",
"author": {
"username": "username",
"type": "author",
"id": "b530d119-83f7-47e5-8c33-2defa1507832",
"host": "https://konnection-server.herokuapp.com/",
"displayName": "username",
"url": "https://konnection-server.herokuapp.com/author/b530d119-83f7-47e5-8c33-2defa1507832",
"github": ""
},
"comment": "This is a comment by username!",
"comment_url": "https://team6-project-socialdistrib.herokuapp.com/author/2bdec9ff7a234e439cae015a40a1ec60/posts/fa61cdf4a7a349ffa8f313e8bed42167/comments",
"contentType": "text/plain"
}
```
* For getting a list of remote posts:
* POST …

remote_comments GET and POST

---

server/author/tests/test_create_author_endpoint.py
server/author/urls.py
server/author/views.py

GET `http://127.0.0.1:8000/api/all-authors` will return a list of all Authors in JSON, including remote authors in Nodes
Included error logging for failed requests to remote servers
Tested with:
- https://cyver.herokuapp.com/
- https://team6-project-socialdistrib.herokuapp.com/

Get all authors including remote authors

---

client/src/ApiUtils.js
client/src/components/Comments/CommentComponent.js
client/src/components/Comments/Comments.scss
client/src/components/Comments/PostComments.js
client/src/components/Post/CreatePostForm.js
client/src/components/SpecificPost/SpecificPostPage.js

Summary:
- Integrated local comment calls
- changed likes visual on comment

Integrate Local Comments

---

client/src/components/Comments/PostComments.js
client/src/components/Feeds/MyFeedPage.js
client/src/components/Feeds/PublicFeedPage.js
client/src/components/Post/PostComponent.js

fix: id fix

---

server/followers/tests/tests_follower_list_endpoint.py
server/followers/views.py

This pr is to enhance the current logic of unfollow to remote the dependency of payload to redirect remote unfollow.

[n/a] fix: unfollow

---

client/src/ApiUtils.js
client/src/components/Comments/PostComments.js
client/src/components/Post/PostComponent.js
client/src/components/Post/PostList.js
client/src/components/SpecificPost/SpecificPostPage.js

**Summary**
- Fixed local comments
- Added calls for remote comments
resolves #121

Remote Comments

---

client/src/ApiUtils.js
client/src/components/Comments/PostComments.js
client/src/components/Feeds/MyFeedPage.js
client/src/components/Feeds/PublicFeedPage.js
client/src/components/Post/PostComponent.js
client/src/components/Post/PostList.js

Summary:
- (hopefully) fixed comments prod bug
- refactored comments to get correct number of comments for post but not make so many calls lmao

refactor: comments

---

client/src/ApiUtils.js
client/src/components/Post/PostList.js

Summary:
- fixes public comments count
- why do i break everything i touch
- remote comments works tho 😍

Fix Public Comments Count

---

server/inbox/admin.py
server/inbox/models.py
server/inbox/serializers.py
server/inbox/views.py
server/posts/models.py
server/posts/tests/test_create_post_endpoint.py

Code cleanup
